- name: copying files
  copy:
    src: test/
    dest: "{{ webroot }}"

- include_vars: test.yaml

- name: copy Jinja2 files
  template:
    src: web.conf.j2
    dest: "{{ web_config }}"
  notify: restart_apache