- name: Install httpd
  yum:
    name: "{{ websvc }}"
    state: installed
- name: start httpd server
  service:
     name: "{{ websvc }}"
- name: Create directory
  file:
    path: "{{ webroot }}"
    state: directory

- name: Import further tasks from other files
  import_tasks: install.yaml