#Playbook Example

- hosts: all
  become: true
  tasks:
    - name: Create directory
      file:
        path:
           - "{{web1}}"
           - "{{webroot}}"
           - "{{web}}"

        state: directory
    - debug:
         msg: "Directories are {{web1}} {{webroot}} {{web}}"



